CREATE  DATABASE BIENES_RAICES
GO
USE BIENES_RAICES
GO

CREATE TABLE TIPO_PROPIEDADES(
IDTIPO INT NOT NULL  PRIMARY KEY IDENTITY(1,1),
DESCRIPCION_TIPO VARCHAR (50) NOT NULL,
ESTADO BIT
)
GO

CREATE TABLE PROPIEDADES(
 IDPROPIEDAD INT NOT NULL PRIMARY  KEY IDENTITY(1,1),
 TIPO_PROPIEDAD INT NOT NULL,
 IDVENDEDOR INT NOT NULL,
 DESCRIPCION VARCHAR(100) NOT NULL,
 CANT_AMBIENTES INT ,
 MTS2 DECIMAL(5,2) NOT NULL CHECK (MTS2>0),
 COCHERA BIT NOT NULL,
 DIRECCION VARCHAR (100) NOT NULL,
 URL_IMAGEN  VARCHAR (300) NOT NULL,
 VENTA BIT NOT NULL,
 PRECIO MONEY NOT NULL CHECK (PRECIO>0),
 ESTADO BIT NOT NULL
)
GO

CREATE TABLE USUARIOS (
IDUSUARIO INT  NOT NULL PRIMARY  KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
FECHA_NACIMIENTO DATE NOT NULL,
NIVEL_ACCESO INT NOT NULL CHECK (NIVEL_ACCESO>=0),
CONTRESEÑA VARCHAR (20) NOT NULL,
ESTADO BIT NOT NULL
)
GO

CREATE TABLE TIPO_USUARIO(
TIPO INT NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR (50) NOT NULL,
ESTADO BIT
)
GO

CREATE TABLE VENDEDORES(
IDVENDEDOR INT NOT NULL PRIMARY  KEY IDENTITY(1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
SEXO CHAR NOT NULL,
LEGAJO VARCHAR (10) NOT NULL,
DNI  VARCHAR (10) NOT NULL,
DOMICILIO VARCHAR (50),
FECHA_INGRESO  DATE  NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
ESTADO BIT NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE
)
GO

CREATE TABLE VISITAS(
IDVISITA INT NOT NULL PRIMARY  KEY IDENTITY(1,1),
IDPROPIEDAD INT NOT NULL,
IDVENDEDOR INT NOT NULL,
IDUSUARIO INT NOT NULL,
FECHA DATETIME NOT NULL,
HORA TIME NOT NULL,
ESTADO BIT NOT NULL
)
GO

SELECT * FROM VISITAS

--INSERT TIPO DE PROPIEDADES---------------------
INSERT INTO TIPO_PROPIEDADES VALUES ('DEPARTAMENTO',1)
INSERT INTO TIPO_PROPIEDADES VALUES ('CASA',1)
INSERT INTO TIPO_PROPIEDADES VALUES ('LOTE',1)
INSERT INTO TIPO_PROPIEDADES VALUES ('DUPLEX',1)
select * from TIPO_PROPIEDADES

-- INSERT PROPIEDADES -------------------
INSERT INTO PROPIEDADES VALUES (1, 10000, 'EXCELENTE UBICACION', 2, 25, 0, 'PRESIDENTE PERON 2332', 'https://decofilia.com/wp-content/uploads/2017/01/mejores-apartamentos-pisos-lujo-mundo-78.jpg',1,95000,1)
INSERT INTO PROPIEDADES VALUES (2, 20000, 'IDEAL FAMILIA TIPO', 5, 65.5, 1, 'PRINGLES 987', 'https://phantom-expansion.unidadeditorial.es/6e465f1d3047c29d8ae05b7e58ebc98a/crop/164x0/1024x573/f/jpg/assets/multimedia/imagenes/2021/10/14/16342349978769.jpg',1,120000,1)
INSERT INTO PROPIEDADES VALUES (3, 30000, 'LOTE EN ZONA DE EXPANCION', 5, 75.2, 0, 'LOS AROLDOS 3321', 'https://www.semana.com/resizer/ktXumP3bvnZUKCPwU52GwWWBebo=/1280x720/smart/filters:format(jpg):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/semana/4KEOUCGM7FDRHGJVNJJWTAF464.jpeg',1,95000,1)
select * from PROPIEDADES


--INSERT USUARIOS---------------------------
INSERT INTO USUARIOS VALUES ('SANTIAGO','LINARES', 'SANTILINARES@GMAIL.COM', '20001010', 2,'123456', 1)
INSERT INTO USUARIOS VALUES ('MATIAS','FALDUTI', 'MATIASF@YAHOO.COM', '19900101', 0,'123456', 1)
INSERT INTO USUARIOS VALUES ('MAXIMILIANO', 'SAR FERNANDEZ', 'MAXI@UTN.COM.AR','19950101', 0,'123456', 1)
select* from USUARIOS

--INSERT TIPO USUARIO----------------------------------
INSERT INTO TIPO_USUARIO VALUES('0','ADMINISTRADOR',1)
INSERT INTO TIPO_USUARIO VALUES('1','VENDEDOR',1)
INSERT INTO TIPO_USUARIO VALUES('2','CLIENTE',1)
select * from TIPO_USUARIO

--INSERT  VENDEDEDORES--------------------------------
INSERT INTO VENDEDORES VALUES ('nombre 1','apellido 1','M','10000','11111111', 'domicilio 1', '01/01/2000', '20001010', 1, 'VENDEDOR1@GMAIL.COM')
INSERT INTO VENDEDORES VALUES ('nombre 2','apellido 2','F','20000','22222222', 'domicilio 2', '02/02/2000', '20001010', 1, 'VENDEDOR2@GMAIL.COM')
INSERT INTO VENDEDORES VALUES ('nombre 3','apellido 3','O','30000','33333333', 'domicilio 3', '03/03/2000', '20001010', 1, 'VENDEDOR3@GMAIL.COM')
select * from VENDEDORES

