--CREATE DATABASE BIENES_RAICES
USE BIENES_RAICES
GO
CREATE TABLE TIPO_PROP(
 IDTIPO INT  PRIMARY KEY IDENTITY (1,1),
 TIPO VARCHAR(50) NOT NULL,

)
GO

CREATE TABLE PROPIEDADES(
 ID INT  PRIMARY KEY IDENTITY (1,1),
 TIPO INT NOT NULL FOREIGN KEY REFERENCES TIPO_PROP (IDTIPO),
 AMBIENTES INT NOT NULL,
 METROS_CUADRADOS DECIMAL (5,2) NOT NULL,
 COCHERA BIT NOT NULL,
 DOMICILIO VARCHAR(50)NOT NULL,
 VENTA BIT NOT NULL,
 URLIMAGEN VARCHAR(300)NOT NULL
)

GO

CREATE TABLE CLIENTES(
    IDCLIENTE INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	DNI VARCHAR(15) NOT NULL ,
	NOMBRE VARCHAR(50)NOT NULL ,
	APELLIDO VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	DOMICILIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
    CONTRASEÑA VARCHAR(100) NOT NULL
)

GO

CREATE TABLE VENDEDOR(
	LEGAJO INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	DNI VARCHAR(15) NOT NULL ,
	NOMBRE VARCHAR(50)NOT NULL ,
	APELLIDO VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	DOMICILIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	FECHA_INGRESO DATE NOT NULL,
)

GO
