USE BIENES_RAICES
GO
------------------------------------------------------- PROPIEDADES--------------------------------------------------------------------------
CREATE PROC  SP_AGREGAR_PROPIEDAD (
 @TIPO_PROPIEDAD INT,
 @IDVENDEDOR INT,
 @DESCRIPCION VARCHAR (100),
 @CANT_AMBIENTES INT,
 @MTS2 DECIMAL (5,2),
 @COCHERA BIT,
 @DIRECCION VARCHAR(100),
 @URL VARCHAR (300),
 @VENTA BIT,
 @PRECIO MONEY,
 @ESTADO BIT
)
AS
BEGIN
INSERT INTO PROPIEDADES (TIPO_PROPIEDAD, DESCRIPCION, CANT_AMBIENTES, MTS2, COCHERA, DIRECCION, URL_IMAGEN, VENTA, PRECIO, ESTADO, IDVENDEDOR)
VALUES (
 @TIPO_PROPIEDAD,
 @DESCRIPCION ,
 @CANT_AMBIENTES ,
 @MTS2,
 @COCHERA, 
 @DIRECCION ,
 @URL,
 @VENTA,
 @PRECIO,
 @ESTADO,
 @IDVENDEDOR
)
END
GO
-----------------------------------------------
CREATE PROC SP_LISTAR_TIPOPROPIEDAD
AS
BEGIN
SELECT TxP.IDTIPO, TxP.DESCRIPCION_TIPO, TxP.ESTADO
FROM TIPO_PROPIEDADES TxP
END
GO
------------------------------------------------
CREATE PROC SP_LISTAR_PROPIEDADES 
AS
BEGIN
SELECT P.IDPROPIEDAD, TxP.IDTIPO, TxP.DESCRIPCION_TIPO, P.DESCRIPCION, P.CANT_AMBIENTES, P.MTS2, P.COCHERA, P.DIRECCION, P.URL_IMAGEN, P.VENTA, P.PRECIO, P.ESTADO, P.IDVENDEDOR
FROM PROPIEDADES P
INNER JOIN TIPO_PROPIEDADES TxP ON TxP.IDTIPO = P.TIPO_PROPIEDAD
END
GO
-----------------------------------------
CREATE  PROC SP_MODIFICAR_PROPIEDAD (
 @IDPROPIEDAD INT,	
 @TIPO_PROPIEDAD INT,
 @DESCRIPCION VARCHAR (100),
 @CANT_AMBIENTES INT,
 @MTS2 DECIMAL (5,2),
 @COCHERA BIT,
 @DIRECCION VARCHAR(100),
 @URL VARCHAR (300),
 @VENTA BIT,
 @PRECIO MONEY,
 @ESTADO BIT,
 @IDVENDEDOR INT
)
AS
BEGIN
UPDATE PROPIEDADES  
SET TIPO_PROPIEDAD = @TIPO_PROPIEDAD, DESCRIPCION = @DESCRIPCION, CANT_AMBIENTES = @CANT_AMBIENTES, MTS2 = @MTS2, 
COCHERA = @COCHERA, DIRECCION = @DIRECCION, URL_IMAGEN = @URL, VENTA = @VENTA, PRECIO = @PRECIO, ESTADO = @ESTADO, IDVENDEDOR = @IDVENDEDOR
WHERE IDPROPIEDAD = @IDPROPIEDAD
END
GO
--exec SP_MODIFICAR_PROPIEDAD 4, 2, 'Miguel jordan', 5, 45, 1, 'prueba', 'https://yt3.ggpht.com/ytc/AMLnZu_BlhhFNg-KfyTSj2anQAvnFeJusznwul2N3-pA=s900-c-k-c0x00ffffff-no-rj', 1, 4554, 1
--exec SP_LISTAR_PROPIEDADES
------------------------------------------------------------------
CREATE PROC SP_ELIMINAR_PROPIEDAD(@IDPROPIEDAD INT)
AS
BEGIN
DELETE PROPIEDADES
WHERE IDPROPIEDAD = @IDPROPIEDAD
END
GO

---------------------------------------------------------------VENDEDORES--------------------------------------------------------------------
CREATE PROC SP_AGREGAR_VENDEDOR (
@APELLIDO VARCHAR(50),
@NOMBRE VARCHAR(50),
@SEXO CHAR,
@LEGAJO VARCHAR (10),
@DNI VARCHAR (10),
@DOMICILIO VARCHAR (50),
@FEC_INGRESO DATE,
@FEC_NAC DATE,
@EMAIL VARCHAR(50),
@ESTADO BIT
)
AS 
BEGIN
INSERT INTO VENDEDORES (APELLIDO,NOMBRE,SEXO,LEGAJO, DNI, DOMICILIO, FECHA_INGRESO, FECHA_NACIMIENTO, ESTADO, EMAIL)
VALUES (
@APELLIDO,
@NOMBRE,
@SEXO,  
@LEGAJO,
@DNI,
@DOMICILIO,
@FEC_INGRESO,
@FEC_NAC,
@ESTADO,
@EMAIL
)
END
GO
--------------------------------------------------------------------------------------
CREATE PROC SP_LISTAR_VENDORES 
AS 
BEGIN
SELECT V.IDVENDEDOR, V.NOMBRE, V.APELLIDO, V.SEXO, V.LEGAJO, V.DNI, V.DOMICILIO, V.FECHA_INGRESO, V.ESTADO, V.EMAIL, V.FECHA_NACIMIENTO
FROM VENDEDORES V
END
GO
--------------------------------------------------
CREATE PROC SP_MODIFICAR_VENDEDOR (
@IDVENDEDOR INT,
@APELLIDO  VARCHAR(50),
@NOMBRE    VARCHAR(50),
@SEXO      CHAR(50),
@LEGAJO VARCHAR (10),
@DNI VARCHAR (10),
@DOMICILIO VARCHAR (50),
@FEC_INGRESO DATE,
@ESTADO BIT,
@EMAIL VARCHAR(50),
@FEC_NAC DATE
)
AS
BEGIN
UPDATE VENDEDORES 
SET APELLIDO = @APELLIDO, NOMBRE = @NOMBRE, SEXO=@SEXO, LEGAJO = @LEGAJO, DNI = @DNI, DOMICILIO = @DOMICILIO, FECHA_INGRESO = @FEC_INGRESO, ESTADO = @ESTADO, FECHA_NACIMIENTO = @FEC_NAC, EMAIL = @EMAIL
WHERE IDVENDEDOR = @IDVENDEDOR
END
GO
----------------------------------------------------------
CREATE PROC SP_ELIMINAR_VENDEDOR(@IDVENDEDOR INT)
AS
BEGIN
DELETE VENDEDORES 
WHERE IDVENDEDOR = @IDVENDEDOR
END
GO
-------------------------------------------------USUARIOS---------------------------------------------------------------------
CREATE PROC SP_AGREGAR_USUARIO (
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR (50),
@EMAIL VARCHAR(50),
@FECHA_NAC DATE,
@NIVEL INT ,
@PASS VARCHAR(20),
@ESTADO BIT
)
AS
BEGIN
INSERT INTO USUARIOS(NOMBRE, APELLIDO, EMAIL, FECHA_NACIMIENTO, NIVEL_ACCESO, CONTRESEÑA, ESTADO)
VALUES(
@NOMBRE,
@APELLIDO,
@EMAIL,
@FECHA_NAC,
@NIVEL,
@PASS,
@ESTADO
)
END
GO
-------------------------------------------------------------------------------
CREATE PROC SP_LISTAR_USUARIO
AS
BEGIN
SELECT U.IDUSUARIO, U.NOMBRE, U.APELLIDO, U.EMAIL, U.FECHA_NACIMIENTO, TxU.TIPO, TxU.DESCRIPCION, U.CONTRESEÑA, U.ESTADO
FROM USUARIOS U
INNER JOIN TIPO_USUARIO TxU ON TxU.TIPO = U.NIVEL_ACCESO
END
GO
--------------------------------------------------------------------
--CREATE PROC SP_BUSCAR_USUARIO
--(
--@user VARCHAR (100),
--@pass  VARCHAR (100)
--)
--AS
--BEGIN
--SELECT U.IDUSUARIO, U.NOMBRE, U.APELLIDO, U.EMAIL, U.FECHA_NACIMIENTO, TxU.TIPO,  U.CONTRESEÑA, U.ESTADO
--FROM USUARIOS U
--INNER JOIN TIPO_USUARIO TxU ON TxU.TIPO = U.NIVEL_ACCESO
--WHERE U.EMAIL=@user and U.CONTRESEÑA=@pass
--END
--GO
--------------------------------------------------------------------
CREATE PROC SP_LISTAR_TIPO_USUARIO
AS
BEGIN 
SELECT TxU.TIPO, TxU.DESCRIPCION, TxU.ESTADO
FROM TIPO_USUARIO TxU
END
GO
--------------------------------------------------------------------
CREATE PROC SP_MODIFICAR_USUARIO(
@IDUSUARIO INT ,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR (50),
@EMAIL VARCHAR(50),
@FECHA_NAC DATE,
@NIVEL INT ,
@PASS VARCHAR(20),
@ESTADO BIT
)
AS 
BEGIN
UPDATE USUARIOS 
SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, EMAIL = @EMAIL, FECHA_NACIMIENTO = @FECHA_NAC,
NIVEL_ACCESO = @NIVEL, CONTRESEÑA = @PASS, ESTADO = @ESTADO
WHERE IDUSUARIO = @IDUSUARIO
END
GO
------------------------------------------------------------
CREATE PROC SP_ELIMINAR_USUARIO(
@IDUSUARIO INT
)
AS
BEGIN
DELETE USUARIOS 
WHERE IDUSUARIO = @IDUSUARIO
END
GO
---------------------------------------------------------
CREATE PROC SP_AGREGAR_USUARIO_REGISTRACION (
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR (50),
@EMAIL VARCHAR(50),
@FECHA_NAC DATE,
@NIVEL INT ,
@PASS VARCHAR(20),
@ESTADO BIT
)
AS
BEGIN
INSERT INTO USUARIOS(NOMBRE, APELLIDO, EMAIL, FECHA_NACIMIENTO, NIVEL_ACCESO, CONTRESEÑA, ESTADO)
VALUES(
@NOMBRE,
@APELLIDO,
@EMAIL,
@FECHA_NAC,
@NIVEL,
@PASS,
@ESTADO
)
END
GO
----------------------------------------------------------------------------------

CREATE PROC SP_BUSCAR_USUARIO(
@USER VARCHAR(100),
@PASS VARCHAR (50)
)
AS 
BEGIN
SELECT  u.IDUSUARIO, u.NIVEL_ACCESO, u.EMAIL, u.CONTRESEÑA
FROM USUARIOS AS U
WHERE U.EMAIL=@USER AND U.CONTRESEÑA=@PASS
END
GO

---------------------------------------------------------------------------
CREATE PROC SP_LISTAR_VISITA 
AS
BEGIN
SELECT V.IDVISITA, V.IDPROPIEDAD, V.IDVENDEDOR, V.IDUSUARIO, V.FECHA, V.HORA, V.ESTADO
FROM VISITAS V
END
GO

CREATE PROC SP_AGREGAR_VISITA (
@IDPROPIEDAD INT,
@IDVENDEDOR INT,
@IDUSUARIO INT,
@FECHA DATE,
@HORA  TIME,
@ESTADO BIT
)
AS 
BEGIN
INSERT INTO VISITAS(IDPROPIEDAD, IDVENDEDOR, IDUSUARIO, FECHA, HORA, ESTADO)
VALUES (
@IDPROPIEDAD,
@IDVENDEDOR,
@IDUSUARIO,
@FECHA,
@HORA,
@ESTADO
)
END
GO
------------------------------------------------------------------------------
CREATE PROC SP_ELIMINAR_VISITA(
@IDVISITA INT
)
AS
BEGIN
DELETE VISITAS 
WHERE IDVISITA = @IDVISITA
END
GO

-------------------------------------------------------------------------
CREATE PROC SP_MODIFICAR_VISITA (
@IDVISTA INT,
@IDPROPIEDAD INT,
@IDVENDEDOR INT,
@IDUSUARIO INT,
@FECHA DATE,
@HORA  TIME,
@ESTADO BIT
)
AS 
BEGIN
UPDATE VISITAS 
SET IDPROPIEDAD = @IDPROPIEDAD, IDVENDEDOR = @IDVENDEDOR, IDUSUARIO = @IDUSUARIO, 
FECHA = @FECHA, HORA = @HORA, ESTADO = 1
WHERE IDVISITA = @IDVISTA
END
GO

---------------------------------------------------------------------------------
--VISITAS X VENDEDORES---------------------------------------------
CREATE PROC SP_LISTAR_VISITAR_PORID (@IDUSUARIO INT)
AS
BEGIN
	SELECT V.IDVISITA, V.IDPROPIEDAD, V.IDVENDEDOR, V.IDUSUARIO, V.FECHA, V.HORA, V.ESTADO 
	FROM VISITAS V
	WHERE V.IDUSUARIO = @IDUSUARIO
END
GO

CREATE PROC SP_LISTAR_VISITAR_PORID_VENDEDOR (@EMAILVEND VARCHAR(50))
AS
BEGIN
	SELECT V.IDVISITA, V.IDPROPIEDAD, V.IDUSUARIO, V.FECHA, V.HORA, V.ESTADO
	FROM VISITAS V
	INNER JOIN PROPIEDADES P ON P.IDPROPIEDAD = V.IDPROPIEDAD
	INNER JOIN VENDEDORES VEN ON VEN.LEGAJO = P.IDVENDEDOR
	WHERE VEN.EMAIL = @EMAILVEND
END
GO

CREATE PROC SP_LISTAR_PROPIEDADES_PORID_VENDEDOR (@EMAILVEND VARCHAR(50))
AS
BEGIN
	SELECT P.IDPROPIEDAD, TxP.IDTIPO, TxP.DESCRIPCION_TIPO, P.DIRECCION, P.VENTA
	FROM PROPIEDADES P
	INNER JOIN TIPO_PROPIEDADES TxP ON TxP.IDTIPO = P.TIPO_PROPIEDAD
	INNER JOIN VENDEDORES VEN ON VEN.LEGAJO = P.IDVENDEDOR
	WHERE VEN.EMAIL = @EMAILVEND
END
GO
----------------------------------------------------------------------------------
--VENDEDOR TRIGGER PARA USUARIO


CREATE TRIGGER TR_ALTA_USUARIOVENDEDOR ON VENDEDORES
AFTER INSERT 
AS
BEGIN
	DECLARE @NOMBRE VARCHAR(50)
	DECLARE @APELLIDO VARCHAR(50)
	DECLARE @EMAIL VARCHAR(50)
	DECLARE @CONTRASENIA VARCHAR(50)
	DECLARE @FECHANAC DATE

	SELECT @NOMBRE = NOMBRE FROM inserted
	SELECT @APELLIDO = APELLIDO FROM inserted
	SELECT @EMAIL = EMAIL FROM inserted
	SELECT @CONTRASENIA = DNI FROM inserted
	SELECT @FECHANAC = FECHA_NACIMIENTO FROM inserted
-----------------------insert en usuarios
	INSERT INTO USUARIOS
	VALUES (@NOMBRE, @APELLIDO, @EMAIL, @FECHANAC, 1, @CONTRASENIA, 1)
END
GO

----------------------------------------------------------------
