------------------------------------------------------- PROPIEDADES--------------------------------------------------------------------------
CREATE PROC  SP_AGREGAR_PROPIEDAD (
 @TIPO_PROPIEDAD INT,
 @DESCRIPCION VARCHAR (100),
 @CANT_AMBIENTES INT,
 @MTS2 DECIMAL (5,2),
 @COCHERA BIT,
 @DIRECCION VARCHAR(100),
 @URL VARCHAR (300),
 @VENTA BIT,
 @PRECIO MONEY,
 @ESTADO BIT
)
AS
BEGIN
INSERT INTO PROPIEDADES (TIPO_PROPIEDAD, DESCRIPCION, CANT_AMBIENTES, MTS2, COCHERA, DIRECCION, URL_IMAGEN, VENTA, PRECIO, ESTADO)
VALUES (
 @TIPO_PROPIEDAD,
 @DESCRIPCION ,
 @CANT_AMBIENTES ,
 @MTS2,
 @COCHERA, 
 @DIRECCION ,
 @URL,
 @VENTA,
 @PRECIO,
 @ESTADO
)
END
GO
-----------------------------------------------
CREATE PROC SP_LISTAR_TIPOPROPIEDAD
AS
BEGIN
SELECT TxP.IDTIPO, TxP.DESCRIPCION_TIPO
FROM TIPO_PROPIEDADES TxP
END
GO
------------------------------------------------
CREATE PROC SP_LISTAR_PROPIEDADES 
AS
BEGIN
SELECT P.IDPROPIEDAD, TxP.IDTIPO, TxP.DESCRIPCION_TIPO, P.DESCRIPCION, P.CANT_AMBIENTES, P.MTS2, P.COCHERA, P.DIRECCION, P.URL_IMAGEN, P.VENTA, P.PRECIO, P.ESTADO
FROM PROPIEDADES P
INNER JOIN TIPO_PROPIEDADES TxP ON TxP.IDTIPO = P.TIPO_PROPIEDAD
END
GO
-----------------------------------------
CREATE  PROC SP_MODIFICAR_PROPIEDAD (
 @IDPROPIEDAD INT,	
 @TIPO_PROPIEDAD INT,
 @DESCRIPCION VARCHAR (100),
 @CANT_AMBIENTES INT,
 @MTS2 DECIMAL (5,2),
 @COCHERA BIT,
 @DIRECCION VARCHAR(100),
 @URL VARCHAR (300),
 @VENTA BIT,
 @PRECIO MONEY,
 @ESTADO BIT
)
AS
BEGIN
UPDATE PROPIEDADES  
SET TIPO_PROPIEDAD = @TIPO_PROPIEDAD, DESCRIPCION = @DESCRIPCION, CANT_AMBIENTES = @CANT_AMBIENTES, MTS2 = @MTS2, 
COCHERA = @COCHERA, DIRECCION = @DIRECCION, URL_IMAGEN = @URL, VENTA = @VENTA, PRECIO = @PRECIO, ESTADO = @ESTADO
WHERE IDPROPIEDAD = @IDPROPIEDAD
END
GO
------------------------------------------------------------------
CREATE PROC SP_ELIMINAR_PROPIEDAD(@IDPROPIEDAD INT)
AS
BEGIN
UPDATE PROPIEDADES SET ESTADO = 0
WHERE IDPROPIEDAD = @IDPROPIEDAD
END
GO

---------------------------------------------------------------VENDEDORES--------------------------------------------------------------------
CREATE PROC SP_AGREGAR_VENDEDOR (
@LEGAJO VARCHAR (10),
@DNI VARCHAR (10),
@DOMICILIO VARCHAR (50),
@FEC_INGRESO DATE,
@ESTADO BIT
)
AS 
BEGIN
INSERT INTO VENDEDORES (LEGAJO, DNI, DOMICILIO, FECHA_INGRESO, ESTADO)
VALUES (
@LEGAJO,
@DNI,
@DOMICILIO,
@FEC_INGRESO,
@ESTADO
)
END
GO
--------------------------------------------------------------------------------------
CREATE PROC SP_LISTAR_VENDORES 
AS 
BEGIN
SELECT V.IDVENDEDOR, V.LEGAJO, V.DNI, V.DOMICILIO, V.FECHA_INGRESO, V.ESTADO
FROM VENDEDORES V
END
GO
--------------------------------------------------
CREATE PROC SP_MODIFICAR_VENDEDOR (
@IDVENDEDOR INT,
@LEGAJO VARCHAR (10),
@DNI VARCHAR (10),
@DOMICILIO VARCHAR (50),
@FEC_INGRESO DATE,
@ESTADO BIT
)
AS
BEGIN
UPDATE VENDEDORES 
SET LEGAJO = @LEGAJO, DNI = @DNI ,DOMICILIO = @DOMICILIO, FECHA_INGRESO = @FEC_INGRESO, ESTADO = @ESTADO
WHERE IDVENDEDOR = @IDVENDEDOR
END
GO
----------------------------------------------------------
CREATE PROC SP_ELIMINAR_VENDEDOR(@IDVENDEDOR INT)
AS
BEGIN
UPDATE VENDEDORES SET ESTADO = 0
WHERE IDVENDEDOR = @IDVENDEDOR
END
GO
-------------------------------------------------USUARIOS---------------------------------------------------------------------
CREATE PROC SP_AGREGAR_USUARIO (
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR (50),
@EMAIL VARCHAR(50),
@FECHA_NAC DATE,
@NIVEL INT ,
@PASS VARCHAR(20),
@ESTADO BIT
)
AS
BEGIN
INSERT INTO USUARIOS(NOMBRE, APELLIDO, EMAIL, FECHA_NACIMIENTO, NIVEL_ACCESO, CONTRESEÑA, ESTADO)
VALUES(
@NOMBRE,
@APELLIDO,
@EMAIL,
@FECHA_NAC,
@NIVEL,
@PASS,
@ESTADO
)
END
GO
-------------------------------------------------------------------------------
CREATE PROC SP_LISTAR_USUARIO
AS
BEGIN
SELECT U.IDUSUARIO, U.NOMBRE, U.APELLIDO, U.EMAIL, U.FECHA_NACIMIENTO, TxU.TIPO, TxU.DESCRIPCION, U.CONTRESEÑA, U.ESTADO
FROM USUARIOS U
INNER JOIN TIPO_USUARIO TxU ON TxU.TIPO = U.NIVEL_ACCESO
END
GO
--------------------------------------------------------------------
CREATE PROC SP_LISTAR_TIPO_USUARIO
AS
BEGIN 
SELECT TxU.TIPO, TxU.DESCRIPCION 
FROM TIPO_USUARIO TxU
END
GO
--------------------------------------------------------------------
CREATE PROC SP_MODIFICAR_USUARIO(
@IDUSUARIO INT ,
@NOMBRE VARCHAR(50),
@APELLIDO VARCHAR (50),
@EMAIL VARCHAR(50),
@FECHA_NAC DATE,
@NIVEL INT ,
@PASS VARCHAR(20),
@ESTADO BIT
)
AS 
BEGIN
UPDATE USUARIOS 
SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, EMAIL = @EMAIL, FECHA_NACIMIENTO = @FECHA_NAC,
NIVEL_ACCESO = @NIVEL, CONTRESEÑA = @PASS, ESTADO = @ESTADO
WHERE IDUSUARIO = @IDUSUARIO
END
GO
------------------------------------------------------------
CREATE PROC SP_ELIMINAR_USUARIO(
@IDUSUARIO INT
)
AS
BEGIN
UPDATE USUARIOS SET ESTADO = 0
WHERE IDUSUARIO = @IDUSUARIO
END
GO
---------------------------------------------------------