
CREATE PROC SP_INSERTAR_PROPIEDAD (
@TIPO   INT,
@AMB    INT,
@MC     DECIMAL(5,2),
@COC     BIT,
@DOMC   VARCHAR(50),
@VEN    BIT,
@URLIMG VARCHAR(300)
)
AS
BEGIN
 INSERT INTO PROPIEDADES (TIPO,AMBIENTES,METROS_CUADRADOS,COCHERA,DOMICILIO,VENTA,URLIMAGEN)
 VALUES (@TIPO ,@AMB,@MC,@COC, @DOMC, @VEN, @URLIMG
 )
END